version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: minicommerce
      POSTGRES_USER: miniuser
      POSTGRES_PASSWORD: minipass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ms-net

  product-service:
    build: ./product-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/minicommerce
      SPRING_DATASOURCE_USERNAME: miniuser
      SPRING_DATASOURCE_PASSWORD: minipass
    ports:
      - "8080"
    depends_on:
      - postgres
    networks:
      - ms-net

  order-service:
    build: ./order-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/minicommerce
      SPRING_DATASOURCE_USERNAME: miniuser
      SPRING_DATASOURCE_PASSWORD: minipass
      INTERNAL_SERVICES_PRODUCT_SERVICE_URL: http://product-service:8080
      INTERNAL_SERVICES_USER_SERVICE_URL: http://user-service:8080
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - product-service
    networks:
      - ms-net

  user-service:
    build: ./user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/minicommerce
      SPRING_DATASOURCE_USERNAME: miniuser
      SPRING_DATASOURCE_PASSWORD: minipass
    ports:
      - "8080"
    depends_on:
      - postgres
    networks:
      - ms-net

networks:
  ms-net:
    driver: bridge

volumes:
  postgres_data:
