

quarkus.smallrye-openapi.enable=true
quarkus.redis.health.enabled=false
quarkus.datasource.health.enabled=true

quarkus.quinoa=false
#quarkus.quinoa.ui-root-path=quinoa
#quarkus.quinoa.package-manager-install=true
#quarkus.quinoa.package-manager-install.node-version=20.10.0

quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=
quarkus.datasource.username=
quarkus.datasource.password=

quarkus.hibernate-orm.packages=tech.noar.dao.entity
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

quarkus.hibernate-orm.jdbc.statement-batch-size=30
quarkus.hibernate-orm.database.generation=none

quarkus.hibernate-orm.unsupported-properties."hibernate.column_ordering_strategy"=tech.noar.configurations.CustomColumnOrderingStrategy

quarkus.hibernate-orm.log.queries-slower-than-ms=200
quarkus.hibernate-orm.log.sql=false

quarkus.jackson.property-naming-strategy=LOWER_CAMEL_CASE
quarkus.jackson.accept-case-insensitive-enums=true

quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=*

quarkus.arc.context-propagation.enabled=true
quarkus.smallrye-health.context-propagation=true


##### LOGGING #####
quarkus.log.level=INFO
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) %s%e%n
quarkus.log.category."org.hibernate".level=INFO


