server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/minicommerce
    username: miniuser
    password: minipass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: 7b7b1253ee80e3ac9aea2f859f3796129e5a50cbaac52b128a82f6e80d8f129b
  expiration: 24