version: "3.8"

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl:ro
      - vault-data:/vault/data
    command: vault server -config=/vault/config/vault.hcl

volumes:
  vault-data:

